Add locking and nice backups

diff --git a/scripts/init b/scripts/init
--- a/scripts/init
+++ b/scripts/init
@@ -98,17 +98,23 @@ mc_stop() {
 }
 
 mc_backup_world() {
-   mc_saveoff
+   if lockfile "$BACKUPPATH/backup.lock"; then
+     echo "Locked backup lockfile"
+   else
+     echo "Failed to lock lockfile"
+     exit 1
+   fi
 
+   mc_saveoff
    local backup_file="$BACKUPPATH/backup.tar"
    echo "Backing up minecraft world..."
    rm -f $backup_file
-   as_user "tar -C \"$MC_HOME\" -cf \"$backup_file\" $WORLD"
+   as_user "nice -n 19 tar -C \"$MC_HOME\" -cf \"$backup_file\" $WORLD"
 
    mc_saveon
 
    echo "Compressing backup..."
-   as_user "gzip -f \"$backup_file\""
+   as_user "nice -n 19 gzip -f \"$backup_file\""
 
    local remote_dir="s3://$BUCKET_NAME/servers/$SERVER_NAME/world_backups/"
    aws s3 ls $remote_dir > /tmp/backup_listing
@@ -120,6 +126,8 @@ mc_backup_world() {
    fi
    aws s3 mv "${backup_file}.gz" "${remote_dir}current.tgz"
 
+   echo "Removing lockfile"
+   rm -f "$BACKUPPATH/backup.lock"
    echo "Done."
 }
 
